"""users table

Revision ID: 16610254e1d8
Revises: 00df1914995c
Create Date: 2019-08-04 16:24:52.744940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16610254e1d8'
down_revision = '00df1914995c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'address', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='foreignkey')
    # ### end Alembic commands ###
